feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 18084
spring:
  application:
    name: cloud-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      datasource:
        ds:
          nacos:
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            rule-type: flow
            server-addr: 127.0.0.1:8848
      eager: true
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
  main:
    allow-bean-definition-overriding: true
